# Generated by Django 3.2.18 on 2023-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230420_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_name',
        ),
    ]
