# Generated by Django 3.2.18 on 2023-04-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_userame', models.CharField(max_length=100)),
                ('patient_username', models.CharField(max_length=100)),
                ('required_speciality', models.TextField(max_length=200)),
                ('appointmentDate', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointmantStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
