# Generated by Django 3.2.18 on 2023-04-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appointmentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetail',
            old_name='appointmantStatus',
            new_name='appointmentStatus',
        ),
        migrations.RenameField(
            model_name='appointmentdetail',
            old_name='doctor_userame',
            new_name='doctor_username',
        ),
    ]
